language: node_js
node_js:
  - "0.12"
install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
script:
  - chmod +x ./build.sh
  - ./build.sh > /dev/null
branches:
  only:
    - raw
cache:
  directories:
    - node_modules
